- hosts: local-win10
  connection: local
  gather_facts: no
  sudo: yes
  vars:
    pathwinc: /mnt/c
    pathwind: /mnt/d
    pathwinusers: "{{ pathwinc }}/Users"
    pathwinextra: "{{ pathwind }}"
    user: admin
    group: "{{ user }}"
    pathhome: "/home/{{ user }}"
    pathhomeu: "{{ pathhome }}/u"
    pathhomev: "{{ pathhome }}/v"
    pathhomew: "{{ pathhome }}/w"
    pathadjunctathis: "{{ pathhome }}/adjuncta"
    pathadjunctav: "{{ pathhomev }}/adjuncta"
  tasks:
    - name: user "{{ user }}"
      user:
        name: "{{ user }}"
        group: "{{ group }}"
        home: "{{ pathhome }}"
        password: "{{ 'changepasswordnow' | password_hash('sha512') }}"
        shell: /bin/bash
        uid: 10001
    - name: symlink "{{ pathhome }}"
      file:
        src: "{{ pathwinusers }}/{{ user }}"
        dest: "{{ pathhome }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        state: link
    - name: create "u v w" on extra drive
      file:
        path: "{{ pathwinextra }}/{{ pathhome }}/{{ item }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        state: directory
      with_items:
        - u
        - v
        - w
    - name: symlink "~/u ~/v ~/w" on extra drive
      file:
        src: "{{ pathwinextra }}/{{ pathhome }}/{{ item }}"
        dest: "{{ pathhome }}/{{ item }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        state: link
      with_items:
        - u
        - v
        - w
    - name: copy adjuncta !!! EXTREMELY SLOW
      copy:
        src: "{{ pathadjunctathis }}"
        dest: "{{ pathhomev }}"
        mode: preserve
        owner: "{{ user }}"
        group: "{{ group }}"
    - name: bash configuration
      copy:
        src: "{{ pathadjunctav }}/config/prog/bash/_copy_to_home/"
        dest: "{{ pathhome }}"
        mode: preserve
        owner: "{{ user }}"
        group: "{{ group }}"
    - name: ViM configuration
      copy:
        src: "{{ pathadjunctav }}/config/prog/vim/_copy_to_home/"
        dest: "{{ pathhome }}"
        mode: preserve
        owner: "{{ user }}"
        group: "{{ group }}"
