- hosts: local-win10
  connection: local
  gather_facts: no
  become: yes
  vars:
    pathwinc: /mnt/c
    pathwinusers: "{{ pathwinc }}/Users"
    user: humano
    group: "{{ user }}"
    pathhome: "/home/{{ user }}"
    pathhomez: "{{ pathhome }}/z"
    pathhomeu: "{{ pathhomez }}/u"
    pathhomev: "{{ pathhomez }}/v"
    pathhomew: "{{ pathhomez }}/w"
    pathadjunctathis: "{{ pathhome }}/adjuncta"
    pathadjunctav: "{{ pathhomev }}/adjuncta"
  tasks:
    - name: user group "{{ user }}"
      group:
        name: "{{ user }}"
        gid: 10001
    - name: user "{{ user }}"
      user:
        create_home: no
        group: "{{ group }}"
        groups: sudo
        home: "{{ pathhome }}"
        name: "{{ user }}"
        password: "{{ 'changepasswordnow' | password_hash('sha512') }}"
        shell: /bin/bash
        uid: 10001
    - name: symlink "{{ pathhome }}"
      file:
        src: "{{ pathwinusers }}/{{ user }}"
        dest: "{{ pathhome }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        state: link
    #- name: copy adjuncta !!! EXTREMELY SLOW
    #  copy:
    #    src: "{{ pathadjunctathis }}"
    #    dest: "{{ pathhomev }}"
    #    mode: preserve
    #    owner: "{{ user }}"
    #    group: "{{ group }}"
    - name: bash configuration
      copy:
        src: "{{ pathadjunctav }}/config/prog/bash/_copy_to_home/"
        dest: "{{ pathhome }}"
        mode: preserve
        owner: "{{ user }}"
        group: "{{ group }}"
    - name: ViM configuration
      copy:
        src: "{{ pathadjunctav }}/config/prog/vim/_copy_to_home/"
        dest: "{{ pathhome }}"
        mode: preserve
        owner: "{{ user }}"
        group: "{{ group }}"
