- hosts: local-win10
  connection: local
  gather_facts: no
  sudo: yes
  vars:
    pathwinc: /mnt/c
    pathwinusers: "{{ pathwinc }}/Users"
  tasks:
    - name: user admin
      user:
        name: admin
        group: admin
        home: /home/admin
        password: "{{ 'changepasswordnow' | password_hash('sha512') }}"
        shell: /bin/bash
        uid: 10001
    - name: symlink /home/admin
      file:
        src: "{{ pathwinusers }}/admin"
        dest: /home/admin
        owner: admin
        group: admin
        state: link
